
# Build worker image (VM template)
image: Visual Studio 2015


init:
  - call "%vsappiddir%..\..\VC\Auxiliary\Build\vcvars32.bat" x86
  - choco install make
  - dir
  - make -C ./cppEDM/src/ -f makefile.windows

