
# Build worker image (VM template)
image: Visual Studio 2015


init:
  - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" 
  - choco install make
  - dir

install:
  - git clone https://github.com/eigenteam/eigen-git-mirror eigen_git
  - move eigen_git/Eigen .
  - make -C ./cppEDM/src/ -f makefile.windows
  - pip install pybind11
  - pip install wheel
  - python setup.py bdist_wheel
