
# Build worker image (VM template)
image: Visual Studio 2015


init:
  - call 'C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat' 
  - choco install make
  - dir
  - make -C ./cppEDM/src/ -f makefile.windows

