
# Build worker image (VM template)
image: Visual Studio 2015

environment:

  matrix:

    # For Python versions available on Appveyor, see
    # https://www.appveyor.com/docs/windows-images-software/#python
    # The list here is complete (excluding Python 2.6, which
    # isn't covered by this document) at the time of writing.

    #- PYTHON: "C:\\Python33"
    - PYTHON: "C:\\Python34"


init:
  #- call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars32.bat"
  #- call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
  - call "C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /x64


  #- call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" amd64
  - choco install make
  - dir

install:
  - git clone https://github.com/eigenteam/eigen-git-mirror eigen_git
  - move eigen_git/Eigen .
  - make -C ./cppEDM/src/ -f makefile.windows
  - "%PYTHON%\\python.exe -m pip install pybind11"
  - "%PYTHON%\\python.exe -m pip install wheel"
  - "%PYTHON%\\python.exe setup.py bdist_wheel"
