matrix:

  include:
    - sudo: required
      services:
        - docker
      env: DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64
           PLAT=manylinux1_x86_64
    #- sudo: required
    #  services:
    #    - docker
    #  env: DOCKER_IMAGE=quay.io/pypa/manylinux1_i686
    #       PRE_CMD=linux32
    #       PLAT=manylinux1_i686
    #- sudo: required
    #  services:
    #    - docker
    #  env: DOCKER_IMAGE=quay.io/pypa/manylinux2010_x86_64
    #       PLAT=manylinux2010_x86_64

install:

  - docker pull $DOCKER_IMAGE
  #- pip install -r requirements.txt

script:

  - docker run --rm -e PLAT=$PLAT -v `pwd`:/io $DOCKER_IMAGE $PRE_CMD /io/travis/build-wheels.sh

  - docker exec build git clone https://github.com/eigenteam/eigen-git-mirror eigen_git
  - docker exec mv eigen_git/Eigen .

  - docker exec make -C cppEDM/src clean
  - docker exec make -C cppEDM/src 

  - pip install pybind11 --user
  - pip install wheel --user

  - python setup.py bdist_wheel

deploy:
  provider: releases
  api_key:
    secure: YOUR_API_KEY_ENCRYPTED
  file: "./dist/*"
  skip_cleanup: true
  on:
    tags: true

