matrix:
  include:
    - sudo: required
      services:
        - docker
      env: DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64
           PLAT=manylinux1_x86_64
    - sudo: required
      services:
        - docker
      env: DOCKER_IMAGE=quay.io/pypa/manylinux1_i686
           PRE_CMD=linux32
           PLAT=manylinux1_i686
    - sudo: required
      services:
        - docker
      env: DOCKER_IMAGE=quay.io/pypa/manylinux2010_x86_64
           PLAT=manylinux2010_x86_64

install:

  - docker pull $DOCKER_IMAGE
  - pip install -r requirements.txt
  - pip install wheel

script:

  - docker run --rm -e PLAT=$PLAT -v `pwd`:/io $DOCKER_IMAGE $PRE_CMD /io/travis/build-wheels.sh

  - git clone https://github.com/eigenteam/eigen-git-mirror eigen_git
  - mv eigen_git/Eigen .

  - make -C cppEDM/src clean
  - make -C cppEDM/src 

  - python setup.py bdist_wheel
