language: python

os: osx

python:
  #- "2.7"
  #- "3.4"
  - "3.5"
  #- "3.6"      
  #- "3.7"
# command to install dependencies
install:
  - pip install -r requirements.txt

script:

  - git clone https://github.com/eigenteam/eigen-git-mirror eigen_git
  - mv eigen_git/Eigen .

  - make -C cppEDM/src clean
  - make -C cppEDM/src 

  - python setup.py bdist_wheel
# command to run tests
#script:
#  - pytest
