variables:
    CIBW_BUILD: cp36-* cp37-* cp38-*
    CIBW_BEFORE_BUILD: yum install -y lapack-devel libpng-devel freetype-devel freetype blas-devel pkg-config; pip install -r requirements.txt; 

strategy:
  matrix:
    Windows_3.8:
      vmImage: 'vs2017-win2016'
      build_name: 'Windows_3.8_EDM'
      python.version: '3.8'

pool:

  vmImage: $(vmImage)
  python.version: $(python.version)

steps:

- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'

- bash: |
    distutils_path=`echo "import distutils,os;print(os.path.dirname(distutils.__file__))"|python`
    echo $'[build]\ncompiler=mingw32' > $distutils_path/distutils.cfg
  displayName: setup mingw compiler option for windows build
  condition: eq( variables['Agent.OS'], 'Windows_NT' )

- script: |
    pip install -r requirements.txt
    pip install --upgrade wheel
    pip install --upgrade setuptools
  displayName: install required python modules for pyEDM build

- script: python setup.py bdist_wheel
  displayName: build pyEDM wheel
  condition: ne( variables['Agent.OS'], 'Linux' )
