
strategy:
  matrix:
    Windows_3.5.4:
      vmImage: 'vs2017-win2016'
      build_name: 'Windows_3.5.4_EDM'
      python.version: '3.5.4'

pool:
  vmImage: $(vmImage)
  python.version: $(python.version)

#only setup the visual studio environment if on windowz
- task: BatchScript@1
  inputs:
    filename: 'C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat'
    arguments: 'amd64'
    modifyEnvironment: True 
  condition: eq( variables['Agent.OS'], 'Windows_NT' )
  displayName: setup visual studio env on windows

steps:

#build cppEDM with respective makefile

- script: make -C cppEDM/src -f makefile.windows clean
  condition: eq( variables['Agent.OS'], 'Windows_NT' )
  displayName: cleaning cppEDM

- script: make -C cppEDM/src -f makefile.windows
  condition: eq( variables['Agent.OS'], 'Windows_NT' )
  displayName: building cppEDM on windows


