# https://docs.microsoft.com/azure/devops/pipelines/languages/python 
pool:
  #vmImage: 'ubuntu-16.04' # other options: 'macOS-10.13', 'vs2017-win2016'
  #vmImage:  'macOS-10.13' #, 'vs2017-win2016'
  vmImage:   'vs2017-win2016'

#strategy:
#    matrix:
#        Python27:
#            python.version: '3.6'

steps:
- task: BatchScript@1
  inputs:
    filename: 'C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat'
    arguments: 'amd64'
    modifyEnvironment: True 
- script: make -C cppEDM/src -f makefile.windows
- script: pip install pybind11
- script: python setup.py build
- publish: $(System.DefaultWorkingDirectory)/bin/WebApp
    artifact: WebApp
