variables:
    CIBW_BUILD: cp36-* cp37-* cp38-*
    CIBW_BEFORE_BUILD: yum install -y lapack-devel libpng-devel freetype-devel freetype blas-devel pkg-config; pip install -r requirements.txt; 

strategy:
  matrix:
    Windows_3.8:
      vmImage: 'vs2017-win2016'
      build_name: 'Windows_3.8_EDM'
      python.version: '3.8'

pool:

  vmImage: $(vmImage)
  python.version: $(python.version)

steps:

- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'

- bash: |
    pyconf_path=`echo "from sysconfig import get_paths;print(get_paths()['include'])"|python`
    sed -i '/#define hypot _hypot/d' $pyconf_path/pyconfig.h
  displayName: remove conflicting hypot bug in pyconf
  condition: eq( variables['Agent.OS'], 'Windows_NT' )

- bash: |
        python -m pip install --upgrade pip
        python -m pip install cibuildwheel==1.1.0 --user
        python -m cibuildwheel --output-dir wheelhouse .
  displayName: manylinux build
  condition: eq( variables['Agent.OS'], 'Linux' )

- task: BatchScript@1
  inputs:
    filename: 'C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat'
    arguments: 'amd64'
    modifyEnvironment: True 
  displayName: setup visual studio env on windows
  condition: eq( variables['Agent.OS'], 'Windows_NT' )

# took this from the scipy azure build script so credit to them in case needed
# JP This hardcoded link to openblas is a problem.  Seems it's gone...
- powershell: |
    $wc = New-Object net.webclient;
    $wc.Downloadfile("https://repo.msys2.org/mingw/x86_64/mingw-w64-x86_64-openblas-0.3.10-2-any.pkg.tar.zst", "openblas.tar.zst")
    $tmpdir = New-TemporaryFile | %{ rm $_; mkdir $_ }
    Expand-Archive "openblas.tar.zst" $tmpdir
    cp $tmpdir\64\lib\libopenblas_v0.3.7-gcc_7_1_0.a $(System.DefaultWorkingDirectory)\\cppEDM\\lib\\libopenblas.a
  displayName: 'download openblas'
  condition: eq( variables['Agent.OS'], 'Windows_NT' )
