
strategy:
  matrix:
    Windows_3.6.8:
      vmImage: 'vs2017-win2016'
      build_name: 'Windows_3.6.8_EDM'

pool:
  vmImage: $(vmImage)

steps:

- script: | 
    mkdir pyEDM/win_64_libs
    curl https://icl.cs.utk.edu/lapack-for-windows/libraries/VisualStudio/3.7.0/Dynamic-MINGW/Win64/liblapack.lib -o pyEDM/win_64_libs/liblapack.lib
    np_path=`echo "import numpy; import os; print(os.path.dirname(numpy.__file__))" | py`
    cp $np_path/.libs/* pyEDM/win_64_libs/
    

#- task: BatchScript@1
#  inputs:
#    filename: 'C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat'
#    arguments: 'amd64'
#    modifyEnvironment: True 
#  condition: eq( variables['Agent.OS'], 'Windows_NT' )
#  displayName: setup visual studio env on windows

#- script: curl https://icl.cs.utk.edu/lapack-for-windows/libraries/VisualStudio/3.5.0/Static-INTEL/Win64/LAPACK.lib --output lapack.lib
#- script: cl test_blas.cc lapack.lib tmp.lib

