
variables:
    CIBW_BUILD: cp38-* cp39-*
    CIBW_BEFORE_BUILD: apt-get install -y lapack-devel libpng-devel freetype-devel freetype blas-devel pkg-config libatlas-base-dev gfortran libblas-dev liblapack-dev; pip install -r requirements.txt;

jobs:
- job:

  pool:
    vmImage: 'ubuntu-latest'
  strategy:
    matrix:
      Python37:
        python.version: '3.9'

  steps:
  - task: UsePythonVersion@0
    displayName: 'Use Python $(python.version)'
    inputs:
      versionSpec: '$(python.version)'

  - script: |
      apt-get install -y lapack-devel
      python -m pip install cibuildwheel==1.10.0
      python -m pip install -r requirements.txt
      python -m pip install --upgrade wheel
      python -m pip install --upgrade setuptools
      python -m cibuildwheel --output-dir wheelhouse
    displayName: install required python modules for pyEDM build

  - task: PublishBuildArtifacts@1
    inputs: {pathtoPublish: 'wheelhouse'}

