variables:
    CIBW_BUILD: cp36-* cp37-* cp38-*
    CIBW_BEFORE_BUILD: yum install -y lapack-devel libpng-devel freetype-devel freetype blas-devel pkg-config; pip install -r requirements.txt; 

strategy:
  matrix:
    Windows_3.8:
      vmImage: 'vs2017-win2016'
      build_name: 'Windows_3.8_EDM'
      python.version: '3.8'

pool:

  vmImage: $(vmImage)
  python.version: $(python.version)

steps:

- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'

- bash: |
    mkdir tmp
    git clone https://github.com/xianyi/OpenBLAS tmp
    cd tmp
    make
    ls
  displayName: cloud building is worst
  condition: eq( variables['Agent.OS'], 'Windows_NT' )
