
strategy:
  matrix:
    Linux_Python36:
      vmImage: 'ubuntu-16.04'
      python.version: '3.6'
      build_name: 'Linux_Python36_EDM'
    Linux_Python37:
      vmImage: 'ubuntu-16.04'
      python.version: '3.7'
      build_name: 'Linux_Python37_EDM'
    Windows_Python36:
      vmImage: 'vs2017-win2016'
      python.version: '3.6'
      build_name: 'Windows_Python36_EDM'
    Windows_Python37:
      vmImage: 'vs2017-win2016'
      python.version: '3.7'
      build_name: 'Windows_Python37_EDM'
    Mac_Python36:
      vmImage: 'macos-10.13'
      python.version: '3.6'
      build_name: 'Mac_Python36_EDM'
    Mac_Python37:
      vmImage: 'macos-10.13'
      python.version: '3.7'
      build_name: 'Mac_Python37_EDM'

pool:
  vmImage: $(vmImage)
  python.version: $(python.version)

steps:
#only setup the visual studio environment if on windowz
- task: BatchScript@1
  inputs:
    filename: 'C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat'
    arguments: 'amd64'
    modifyEnvironment: True 
  condition: eq( variables['Agent.OS'], 'Windows_NT' )
  displayName: setup visual studio env on windows

#download eigen for cppEDM
- script: git clone https://github.com/eigenteam/eigen-git-mirror eigen_git
  displayName: download eigen
- script: mv eigen_git/Eigen .

#print which version python using for testing
- script: python --version

#build cppEDM with respective makefile
- script: make -C cppEDM/src -f makefile.windows
  condition: eq( variables['Agent.OS'], 'Windows_NT' )
  displayName: building cppEDM on windows
- script: make -C cppEDM/src
  condition: eq( variables['Agent.OS'], 'Darwin' )
  displayName: building cppEDM on macOS
- script: make -C cppEDM/src 
  condition: eq( variables['Agent.OS'], 'Linux' )
  displayName: building cppEDM on linux

#build the package and download
- script: pip install pybind11
- script: python setup.py build

- publish: $(System.DefaultWorkingDirectory)/build
  condition: eq( variables['Agent.OS'], 'Darwin' )
  artifact: $(build_name)
- publish: $(System.DefaultWorkingDirectory)/build
  condition: eq( variables['Agent.OS'], 'Linux' )
  artifact: $(build_name)
- publish: $(System.DefaultWorkingDirectory)/build
  condition: eq( variables['Agent.OS'], 'Windows_NT' )
  artifact: $(build_name)
