
strategy:
  matrix:
    Windows_3.6.8:
      vmImage: 'vs2017-win2016'
      build_name: 'Windows_3.6.8_EDM'
      python.version: '3.6.8'

pool:
  vmImage: $(vmImage)
  python.version: $(python.version)

steps:

- bash: link /LTCG

#only setup the visual studio environment if on windowz
- task: BatchScript@1
  inputs:
    filename: 'C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat'
    arguments: 'amd64'
    modifyEnvironment: True 
  condition: eq( variables['Agent.OS'], 'Windows_NT' )
  displayName: setup visual studio env on windows

- bash: link /LTCG


#- powershell: Write-Host "##vso[task.prependpath]$env:CONDA\Scripts"
#  displayName: Add conda to PATH

#- script: conda create --yes --quiet --name myEnvironment
#  displayName: create conda env

#- bash: source activate myEnvironment; conda install --yes --name myEnvironment -c conda-forge lapack 
#  displayName: install lapack
#- bash: source activate myEnvironment; conda install --yes --name myEnvironment -c conda-forge blas;
#  displayName: install blas

#build cppEDM with respective makefile
#- script: make -C cppEDM/src -f makefile.windows
#  condition: eq( variables['Agent.OS'], 'Windows_NT' )
#  displayName: building cppEDM on windows

#- task: UsePythonVersion@0
#  inputs:
#    versionSpec: '$(python.version)'

#build the package and download
#- script: pip install pybind11
#- script: pip install wheel
#- task: BatchScript@1
#  inputs:
#    filename: 'C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat'
#    arguments: 'amd64'
#    modifyEnvironment: True 
#  displayName: setup visual studio env on windows

#- bash:  python setup.py bdist_wheel

