jobs:
- job:

  pool:
    vmImage: 'ubuntu-16.04'
  strategy:
    matrix:
      Python36:
        python.version: '3.8'
      Python37:
        python.version: '3.9'

  steps:
  - task: UsePythonVersion@0
    displayName: 'Use Python $(python.version)'
    inputs:
      versionSpec: '$(python.version)'

  - script: |
      python -m pip install cibuildwheel==1.10.0
      pip install -r requirements.txt
      pip install --upgrade wheel
      pip install --upgrade setuptools
      python -m cibuildwheel --output-dir wheelhouse
    displayName: install required python modules for pyEDM build

  - script: tox -e py
    displayName: 'Run Tox'

