variables:
    CIBW_BUILD: cp36-* cp37-* cp38-* cp39-*
    CIBW_BEFORE_BUILD: yum install -y lapack-devel libpng-devel freetype-devel freetype blas-devel pkg-config; pip install -r requirements.txt; 

strategy:
  matrix:
    Linux_3.8:
      vmImage: 'ubuntu-latest'
      build_name: 'manylinux38'
      python.version: '3.8'
    Linux_3.9:
      vmImage: 'ubuntu-latest'
      build_name: 'manylinux39'
      python.version: '3.9'

pool:

  vmImage: $(vmImage)
  python.version: $(python.version)

steps:

- task: UsePythonVersion@0
  displayName: 'Use Python $(python.version)'
  inputs:
    versionSpec: '$(python.version)'

- script: |
      python -m pip install cibuildwheel==1.10.0
      pip install -r requirements.txt
      pip install --upgrade wheel
      pip install --upgrade setuptools
      python -m cibuildwheel --output-dir wheelhouse
  displayName: manylinux build
  condition: eq( variables['Agent.OS'], 'Linux' )

  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: 'wheelhouse'
      artifactName: MyBuildOutputs

