# https://docs.microsoft.com/azure/devops/pipelines/languages/python
pool:
  vmImage: 'ubuntu-16.04' # other options: 'macOS-10.13', 'vs2017-win2016'

strategy:
    matrix:
      Python27:
        python.version: '3.6'

steps:
    - script: make -C cppEDM/src
