variables:
    CIBW_BUILD: cp36-*
    CIBW_BEFORE_BUILD: pip install -r requirements.txt; apt-get install liblapack-dev libblas-dev


jobs:

- job: linux
  pool: {vmImage: 'Ubuntu-16.04'}
  steps:
    - task: UsePythonVersion@0
    - bash: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install cibuildwheel==1.1.0
        cibuildwheel --output-dir wheelhouse .
    - task: PublishBuildArtifacts@1
      inputs: {pathtoPublish: 'wheelhouse'}
