
strategy:
  matrix:
    Windows_3.5:
      vmImage: 'vs2017-win2016'
      build_name: 'Windows_3.5_EDM'
      python.version: '3.5'
    Windows_3.6:
      vmImage: 'vs2017-win2016'
      build_name: 'Windows_3.6_EDM'
      python.version: '3.6'
    Windows_3.7:
      vmImage: 'vs2017-win2016'
      build_name: 'Windows_3.7_EDM'
      python.version: '3.7'
    MacOS_3.5:
      vmImage: 'macos-10.13'
      build_name: 'MacOS_3.5_EDM'
      python.version: '3.5'
    MacOS_3.6:
      vmImage: 'macos-10.13'
      build_name: 'MacOS_3.6.9_EDM'
      python.version: '3.6'
    MacOS_3.7:
      vmImage: 'macos-10.13'
      build_name: 'MacOS_3.7_EDM'
      python.version: '3.7'

pool:

  vmImage: $(vmImage)
  python.version: $(python.version)

steps:

- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'

- bash: |
    pyconf_path=`echo "from sysconfig import get_paths;print(get_paths()['include'])"|python`
    sed -i '/#define hypot _hypot/d' $pyconf_path/pyconfig.h
  displayName: remove conflicting hypot bug in pyconf
  condition: eq( variables['Agent.OS'], 'Windows_NT' )

- task: BatchScript@1
  inputs:
    filename: 'C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat'
    arguments: 'amd64'
    modifyEnvironment: True 
  displayName: setup visual studio env on windows
  condition: eq( variables['Agent.OS'], 'Windows_NT' )

# took this from the scipy azure build script so credit to them in case needed
- powershell: |
    $wc = New-Object net.webclient;
    $wc.Downloadfile("https://3f23b170c54c2533c070-1c8a9b3114517dc5fe17b7c3f8c63a43.ssl.cf2.rackcdn.com/openblas-v0.3.7-win_amd64-gcc_7_1_0.zip", "openblas.zip")
    $tmpdir = New-TemporaryFile | %{ rm $_; mkdir $_ }
    Expand-Archive "openblas.zip" $tmpdir
    cp $tmpdir\64\lib\libopenblas_v0.3.7-gcc_7_1_0.a $(System.DefaultWorkingDirectory)\\cppEDM\\lib\\libopenblas.a
  displayName: 'download openblas'
  condition: eq( variables['Agent.OS'], 'Windows_NT' )

- bash: |
    distutils_path=`echo "import distutils,os;print(os.path.dirname(distutils.__file__))"|python`
    echo $'[build]\ncompiler=mingw32' > $distutils_path/distutils.cfg
  displayName: setup mingw compiler option for windows build
  condition: eq( variables['Agent.OS'], 'Windows_NT' )

- script: |
    pip install -r requirements.txt
    pip install wheel
  displayName: install required python modules for pyEDM build

- script: python setup.py bdist_wheel
  displayName: build pyEDM wheel

- publish: $(System.DefaultWorkingDirectory)/dist
  artifact: $(build_name)
